// constants/mockData.ts
// Separate mock data file - NOT imported in production

import type { Application, JobPost } from '@/hooks/helper';

export const MOCK_JOBS: JobPost[] = [
  {
    job_post_id: "1",
    parent_id: "2",
    title: "Live-in Yaya Needed",
    description: "We are a young family looking for a caring yaya...",
    employment_type: "Live-in",
    work_schedule: "Full-time",
    salary_offered: 8000,
    salary_period: "Monthly",
    province: "Leyte",
    municipality: "Ormoc City",
    distance: 1.2,
    category_ids: ["2"],
    categories: ["Yaya"],
    job_ids: ["5"],
    jobs: ["Yaya"],
    skill_ids: ["9", "11"],
    skills: ["Infant Care", "Child Development"],
    provides_meals: true,
    provides_accommodation: true,
    provides_sss: true,
    provides_philhealth: true,
    provides_pagibig: true,
    vacation_days: 15,
    sick_days: 10,
    days_off: ["Sunday"],
    status: "Open",
    posted_at: "2 hours ago",
    parent_name: "Cruz Family",
    parent_verified: true,
    parent_rating: 4.8,
    match_score: 92,
    match_reasons: ["Category matches", "Location nearby", "Salary in range"],
    is_saved: false,
  },
  {
    job_post_id: "2",
    parent_id: "3",
    title: "Part-time Cook Needed",
    description: "Looking for a skilled cook...",
    employment_type: "Live-out",
    work_schedule: "Part-time",
    salary_offered: 400,
    salary_period: "Daily",
    province: "Leyte",
    municipality: "Ormoc City",
    distance: 4.5,
    category_ids: ["3"],
    categories: ["Cook"],
    job_ids: ["7"],
    jobs: ["Cook"],
    skill_ids: ["15", "16"],
    skills: ["Filipino Cuisine", "Meal Planning"],
    provides_meals: true,
    provides_sss: false,
    provides_philhealth: false,
    provides_pagibig: false,
    days_off: ["Tuesday", "Thursday", "Saturday", "Sunday"],
    status: "Open",
    posted_at: "1 day ago",
    parent_name: "Santos Family",
    parent_verified: true,
    match_score: 78,
    match_reasons: ["Location nearby", "Part-time matches"],
    is_saved: false,
  },
  {
    job_post_id: "3",
    parent_id: "4",
    title: "General Househelp",
    description: "Seeking reliable househelp...",
    employment_type: "Live-in",
    work_schedule: "Full-time",
    salary_offered: 7500,
    salary_period: "Monthly",
    province: "Leyte",
    municipality: "Ormoc City",
    distance: 2.3,
    category_ids: ["1"],
    categories: ["General Househelp"],
    job_ids: ["1", "2"],
    jobs: ["Househelp", "Laundry"],
    skill_ids: [],
    skills: [],
    provides_meals: true,
    provides_accommodation: true,
    provides_sss: true,
    provides_philhealth: true,
    provides_pagibig: false,
    vacation_days: 10,
    sick_days: 5,
    days_off: [],
    status: "Open",
    posted_at: "3 days ago",
    parent_name: "Garcia Family",
    parent_verified: false,
    match_score: 65,
    match_reasons: ["Location nearby"],
    is_saved: true,
    saved_at: "2 days ago",
  },
];

export const MOCK_RECOMMENDATIONS: JobPost[] = [
  // Similar structure, 3-5 jobs with high match scores
  {
    job_post_id: "10",
    parent_id: "7",
    title: "Live-in Yaya for Newborn",
    employment_type: "Live-in",
    work_schedule: "Full-time",
    salary_offered: 9500,
    salary_period: "Monthly",
    province: "Leyte",
    municipality: "Ormoc City",
    distance: 1.8,
    category_ids: ["2"],
    categories: ["Yaya"],
    job_ids: ["5"],
    jobs: ["Yaya"],
    skill_ids: ["9", "11"],
    skills: ["Infant Care", "Child Development"],
    provides_meals: true,
    provides_accommodation: true,
    provides_sss: true,
    provides_philhealth: true,
    provides_pagibig: true,
    vacation_days: 15,
    sick_days: 10,
    days_off: ["Sunday"],
    status: "Open",
    posted_at: "1 hour ago",
    parent_name: "Mendoza Family",
    parent_verified: true,
    match_score: 95,
    match_reasons: [
      "Category matches your profile",
      "Very close to your location",
      "Salary above your range",
      "Requires skills you have"
    ],
    is_saved: false,
    description: "Need experienced yaya for newborn care...",
  },
];

export const MOCK_APPLICATIONS: Application[] = [ 
  {
    application_id: "1",
    job_post_id: "1",
    helper_id: "1",
    cover_letter: "Dear Hiring Manager,\n\nI am writing to express my strong interest in the Live-in Yaya position. With over 3 years of experience in childcare, I am confident in my ability to provide excellent care for your 2-year-old child.\n\nBest regards,\nMaria Santos",
    status: "Shortlisted",
    applied_at: "2 days ago",
    reviewed_at: "1 day ago",
    job_title: "Live-in Yaya Needed",
    job_description: "We are a young family looking for a caring yaya...",
    employment_type: "Live-in",
    work_schedule: "Full-time",
    salary_offered: 8000,
    salary_period: "Monthly",
    municipality: "Ormoc City",
    province: "Leyte",
    parent_id: "2",
    parent_name: "Cruz Family",
    parent_verified: true,
    parent_rating: 4.8,
    job_status: "Open",
  },
  {
    application_id: "2",
    job_post_id: "2",
    helper_id: "1",
    cover_letter: "Hello,\n\nI am interested in the part-time cook position. I have experience cooking Filipino and Western dishes and am available Monday, Wednesday, and Friday as requested.",
    status: "Pending",
    applied_at: "5 hours ago",
    job_title: "Part-time Cook Needed",
    job_description: "Looking for a skilled cook...",
    employment_type: "Live-out",
    work_schedule: "Part-time",
    salary_offered: 400,
    salary_period: "Daily",
    municipality: "Ormoc City",
    province: "Leyte",
    parent_id: "3",
    parent_name: "Santos Family",
    parent_verified: true,
    job_status: "Open",
  },
  {
    application_id: "3",
    job_post_id: "5",
    helper_id: "1",
    cover_letter: "Good day!\n\nI am applying for the general househelp position. I have experience with cleaning, laundry, and light cooking.",
    status: "Rejected",
    parent_notes: "Thank you for applying. We've decided to move forward with another candidate whose experience better matches our needs.",
    applied_at: "1 week ago",
    reviewed_at: "5 days ago",
    job_title: "General Househelp",
    job_description: "Seeking reliable househelp...",
    employment_type: "Live-in",
    work_schedule: "Full-time",
    salary_offered: 7000,
    salary_period: "Monthly",
    municipality: "Tacloban City",
    province: "Leyte",
    parent_id: "4",
    parent_name: "Garcia Family",
    parent_verified: false,
    job_status: "Filled",
  },
]