// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    // .expo/ is regenerated by the dev server and contains Expo's own
    // scaffolding, including a _error.js that imports a path only resolvable
    // inside Expo's build. Linting it reported a broken import in a file
    // nobody wrote and nobody ships.
    ignores: ['dist/*', '.expo/*', 'android/*', 'ios/*'],
  },
  {
    rules: {
      // Off deliberately, not out of laziness about the 44 hits it produced.
      //
      // react/no-unescaped-entities exists because a raw apostrophe or quote in
      // HTML JSX can collide with the surrounding markup. CareLink's text lives
      // in React Native <Text>, which takes a string — there is no markup for a
      // quote to break out of. React escapes text nodes on the web build too,
      // so there is no XSS angle either.
      //
      // Leaving it on meant every ordinary sentence — "You're all caught up",
      // "the helper's profile" — was reported as an error, which is how 44
      // non-problems came to outnumber the one real one in the same list.
      'react/no-unescaped-entities': 'off',
    },
  },
]);
