import { Platform, StyleSheet } from 'react-native';
import { FontFamily } from '@/constants/GlobalStyles';
import { DARK, MUTED, ORANGE, GREEN, BLUE, DIVIDER, ICON_BG, SURFACE, OVERLAY } from '@/components/helper/home/helperWarmTheme';

const WARNING = '#D97706';

const CARD_SHADOW = Platform.select({
  ios:     { shadowColor: '#8B5E3C', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.1, shadowRadius: 18 },
  android: { elevation: 4 },
  default: { boxShadow: '0 6px 24px rgba(139,94,60,0.1)' } as any,
});

export function createHelperWorkScheduleStyles() {
  return StyleSheet.create({
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    scroll: { paddingBottom: 16 },
    requestBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: ORANGE,
      paddingVertical: 14,
      borderRadius: 14,
      marginTop: 20,
    },
    requestBtnText: { fontFamily: FontFamily.fredokaSemiBold, color: '#fff', fontSize: 16 },
    weekNav: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    navBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: ICON_BG,
      alignItems: 'center',
      justifyContent: 'center',
    },
    navBtnDisabled: { opacity: 0.35 },
    weekLabel: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 15, color: DARK },
    cardList: { gap: 10 },
    dayCard: {
      borderRadius: 14,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: DIVIDER,
      padding: 14,
    },
    dayHead: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    dayHeadLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    statusDot: { width: 10, height: 10, borderRadius: 5 },
    dayName: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 15, color: DARK },
    dayDate: { fontFamily: FontFamily.fredokaRegular, fontSize: 13, color: MUTED },
    dayBody: { gap: 4 },
    ok: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 14, color: GREEN },
    time: { fontFamily: FontFamily.fredokaRegular, fontSize: 13, color: DARK },
    timeOut: { fontFamily: FontFamily.fredokaRegular, fontSize: 13, color: MUTED },
    pendingOut: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 13, color: WARNING },
    muted: { fontFamily: FontFamily.fredokaRegular, fontSize: 14, color: MUTED },
    statusLabel: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 14 },
    statusLeave: { color: WARNING },
    statusHoliday: { color: BLUE },
    modalOverlay: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: OVERLAY,
      ...Platform.select({
        web: { justifyContent: 'center', padding: 20 },
        default: { justifyContent: 'flex-end' },
      }),
    },
    modalCard: {
      width: '100%',
      maxWidth: 520,
      alignSelf: 'center',
      backgroundColor: SURFACE,
      padding: 24,
      paddingBottom: 36,
      ...CARD_SHADOW,
      ...Platform.select({
        web: { borderRadius: 20, maxHeight: '90%' as const },
        default: { borderTopLeftRadius: 20, borderTopRightRadius: 20 },
      }),
    },
    modalTitle: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 20, color: DARK, marginBottom: 16 },
    modalLabel: {
      fontFamily: FontFamily.fredokaSemiBold,
      fontSize: 13,
      color: MUTED,
      marginBottom: 8,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    datePickRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderWidth: 1,
      borderColor: DIVIDER,
      borderRadius: 12,
      padding: 14,
      marginBottom: 16,
    },
    datePickText: { flex: 1, fontFamily: FontFamily.fredokaSemiBold, fontSize: 16, color: DARK },
    reasonInput: {
      borderWidth: 1,
      borderColor: DIVIDER,
      borderRadius: 12,
      padding: 14,
      fontSize: 16,
      fontFamily: FontFamily.fredokaRegular,
      color: DARK,
      minHeight: 88,
      textAlignVertical: 'top',
      marginBottom: 20,
    },
    modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12 },
    modalCancel: { paddingVertical: 12, paddingHorizontal: 16 },
    modalCancelText: { fontFamily: FontFamily.fredokaSemiBold, color: MUTED },
    modalSubmit: {
      backgroundColor: ORANGE,
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 12,
      minWidth: 120,
      alignItems: 'center',
    },
    modalSubmitDisabled: { opacity: 0.6 },
    modalSubmitText: { fontFamily: FontFamily.fredokaSemiBold, color: '#fff', fontSize: 16 },
    balanceText: {
      fontFamily: FontFamily.fredokaSemiBold,
      fontSize: 15,
      color: DARK,
      marginBottom: 12,
      textAlign: 'center',
    },
    legendRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 12,
      justifyContent: 'center',
    },
    legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    legendDot: { width: 10, height: 10, borderRadius: 5 },
    legendText: { fontFamily: FontFamily.fredokaRegular, fontSize: 11, color: MUTED },
    sheetSection: { marginTop: 12, gap: 4 },
    sheetLabel: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 12, color: MUTED, textTransform: 'uppercase' },
    sheetValue: { fontFamily: FontFamily.fredokaRegular, fontSize: 16, color: DARK },
    pickerWrap: {
      borderWidth: 1,
      borderColor: DIVIDER,
      borderRadius: 12,
      marginBottom: 16,
      overflow: 'hidden',
    },
    picker: { width: '100%' },
    previewBox: {
      marginBottom: 16,
      padding: 12,
      borderRadius: 12,
      backgroundColor: ICON_BG,
    },
    previewLine: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 14, color: DARK },
    previewWarn: {
      marginTop: 8,
      fontFamily: FontFamily.fredokaSemiBold,
      fontSize: 13,
      color: WARNING,
      lineHeight: 18,
    },
  });
}

export type HelperWorkScheduleStyles = ReturnType<typeof createHelperWorkScheduleStyles>;
