import { Platform, StyleSheet } from 'react-native';
import { FontFamily } from '@/constants/GlobalStyles';
import { DARK, MUTED, ORANGE, GREEN, ICON_BG, WARNING_BG, DIVIDER, SURFACE, OVERLAY } from '@/components/helper/home/helperWarmTheme';

const WARNING = '#D97706';

const CARD_SHADOW = Platform.select({
  ios:     { shadowColor: '#8B5E3C', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 12 },
  android: { elevation: 2 },
  default: { boxShadow: '0 4px 16px rgba(139,94,60,0.08)' } as any,
});

export function createHelperWorkTasksStyles() {
  return StyleSheet.create({
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    listContent: { paddingBottom: 16, gap: 8 },
    empty: { textAlign: 'center', fontFamily: FontFamily.fredokaRegular, color: MUTED, marginTop: 48, fontSize: 15, paddingHorizontal: 24 },
    sectionTitle: {
      fontFamily: FontFamily.fredokaSemiBold,
      fontSize: 13,
      color: MUTED,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginTop: 12,
      marginBottom: 8,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      padding: 14,
      borderRadius: 14,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: DIVIDER,
      marginBottom: 8,
    },
    rowDone: { opacity: 0.55 },
    title: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 16, color: DARK },
    titleDone: { textDecorationLine: 'line-through', color: MUTED },
    desc: { fontFamily: FontFamily.fredokaRegular, fontSize: 14, color: MUTED, marginTop: 4, lineHeight: 20 },
    descDone: { color: MUTED },
    metaRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
    meta: { fontFamily: FontFamily.fredokaRegular, fontSize: 12, color: MUTED },
    metaWarn: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 12, color: WARNING },
    photoLink: { fontFamily: FontFamily.fredokaRegular, fontSize: 11, color: MUTED, marginTop: 4, fontStyle: 'italic' },

    instructionCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: ICON_BG,
      borderRadius: 14,
      padding: 14,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: DIVIDER,
    },
    instructionTitle: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 14, color: DARK, marginBottom: 6 },
    instructionBody: { fontFamily: FontFamily.fredokaRegular, fontSize: 13, color: MUTED, lineHeight: 20 },
    checkInCta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      alignSelf: 'flex-start',
      marginTop: 12,
      backgroundColor: ORANGE,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 10,
    },
    checkInCtaText: { fontFamily: FontFamily.fredokaSemiBold, color: '#fff', fontSize: 14 },
    restHint: { marginTop: 10, fontFamily: FontFamily.fredokaRegular, fontSize: 12, color: MUTED, fontStyle: 'italic' },

    modalOverlay: {
      flex: 1,
      backgroundColor: OVERLAY,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalCenter: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', width: '100%' },
    modalCard: {
      width: '100%',
      maxWidth: 440,
      alignSelf: 'center',
      backgroundColor: SURFACE,
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
      borderColor: DIVIDER,
      ...CARD_SHADOW,
    },
    modalTitle: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 18, color: DARK, marginBottom: 8 },
    modalTaskTitle: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 16, color: DARK, marginBottom: 12 },
    reqPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      alignSelf: 'flex-start',
      backgroundColor: WARNING_BG,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      marginBottom: 12,
    },
    reqPillText: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 13, color: WARNING },
    modalHint: { fontFamily: FontFamily.fredokaRegular, fontSize: 13, color: MUTED, marginBottom: 12 },
    photoRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
    photoBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: DIVIDER,
      backgroundColor: SURFACE,
    },
    photoBtnText: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 14, color: ORANGE },
    pickedLabel: { fontFamily: FontFamily.fredokaRegular, fontSize: 12, color: GREEN, marginBottom: 12 },
    modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, marginTop: 8 },
    modalCancel: { paddingVertical: 12, paddingHorizontal: 8 },
    modalCancelText: { fontFamily: FontFamily.fredokaSemiBold, color: MUTED },
    modalSave: {
      backgroundColor: ORANGE,
      paddingVertical: 12,
      paddingHorizontal: 22,
      borderRadius: 12,
      minWidth: 110,
      alignItems: 'center',
    },
    modalSaveText: { fontFamily: FontFamily.fredokaSemiBold, color: '#fff' },
  });
}
