import { Platform, StyleSheet } from 'react-native';
import { FontFamily } from '@/constants/GlobalStyles';
import {
  DARK, MUTED, SUBTLE, ORANGE, GREEN, ICON_BG, WARNING_BG, DIVIDER, SURFACE, OVERLAY,
  DANGER, DANGER_BG, SUCCESS_BG, INFO, INFO_BG,
} from '@/components/helper/home/helperWarmTheme';

const WARNING = '#D97706';

const CARD_SHADOW = Platform.select({
  ios:     { shadowColor: '#8B5E3C', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 12 },
  android: { elevation: 2 },
  default: { boxShadow: '0 4px 16px rgba(139,94,60,0.08)' } as any,
});

const HERO_SHADOW = Platform.select({
  ios:     { shadowColor: '#1E0A04', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.25, shadowRadius: 16 },
  android: { elevation: 6 },
  default: { boxShadow: '0 8px 24px rgba(30,10,4,0.25)' } as any,
});

export function createHelperWorkTasksStyles() {
  return StyleSheet.create({
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    listContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 16 },

    // ── Header / hero ──────────────────────────────────────────────────────
    header: { marginBottom: 4 },
    hero: { borderRadius: 22, padding: 18, marginBottom: 16, ...HERO_SHADOW },
    heroTitle: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 21, color: '#fff' },
    heroSubtitle: { fontFamily: FontFamily.fredokaRegular, fontSize: 13, color: SUBTLE, marginTop: 4, marginBottom: 16, lineHeight: 18 },
    heroStatsRow: { flexDirection: 'row', gap: 8 },
    heroStatTile: {
      flex: 1,
      backgroundColor: 'rgba(255,255,255,0.07)',
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 4,
      alignItems: 'center',
      gap: 4,
    },
    heroStatIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.10)',
      marginBottom: 2,
    },
    heroStatValue: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 18, color: '#fff' },
    heroStatLabel: { fontFamily: FontFamily.fredokaRegular, fontSize: 10.5, color: SUBTLE, textAlign: 'center' },

    // ── Check-in / rest-day banners ────────────────────────────────────────
    checkInBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: DANGER_BG,
      borderRadius: 16,
      padding: 14,
      marginBottom: 16,
      ...CARD_SHADOW,
    },
    checkInBannerIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 12,
      backgroundColor: SURFACE,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkInBannerText: { flex: 1, fontFamily: FontFamily.fredokaSemiBold, fontSize: 13, color: DARK, lineHeight: 18 },
    checkInBannerCta: {
      backgroundColor: DANGER,
      paddingVertical: 9,
      paddingHorizontal: 14,
      borderRadius: 10,
    },
    checkInBannerCtaText: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 12, color: '#fff' },
    restDayBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: SUCCESS_BG,
      borderRadius: 16,
      padding: 14,
      marginBottom: 16,
      ...CARD_SHADOW,
    },
    restDayBannerIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 12,
      backgroundColor: SURFACE,
      alignItems: 'center',
      justifyContent: 'center',
    },
    restDayBannerText: { flex: 1, fontFamily: FontFamily.fredokaSemiBold, fontSize: 13, color: DARK, lineHeight: 18 },
    previewBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: INFO_BG,
      borderRadius: 16,
      padding: 14,
      marginBottom: 16,
      ...CARD_SHADOW,
    },
    previewBannerIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 12,
      backgroundColor: SURFACE,
      alignItems: 'center',
      justifyContent: 'center',
    },
    previewBannerText: { flex: 1, fontFamily: FontFamily.fredokaSemiBold, fontSize: 13, color: DARK, lineHeight: 18 },

    // ── Filter segmented control ──────────────────────────────────────────
    filterSegment: {
      flexDirection: 'row',
      gap: 4,
      backgroundColor: SURFACE,
      borderRadius: 16,
      padding: 4,
      borderWidth: 1,
      borderColor: DIVIDER,
      marginBottom: 16,
      ...CARD_SHADOW,
    },
    filterPill: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 1,
      paddingVertical: 9,
      borderRadius: 12,
    },
    filterPillActive: { backgroundColor: ORANGE },
    filterPillText: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 12, color: MUTED },
    filterPillTextActive: { color: '#fff' },
    filterPillCount: { fontFamily: FontFamily.fredokaRegular, fontSize: 10.5, color: SUBTLE },
    filterPillCountActive: { color: 'rgba(255,255,255,0.85)' },

    // ── Proof-required banner ──────────────────────────────────────────────
    proofBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: ICON_BG,
      borderRadius: 14,
      padding: 12,
      marginBottom: 4,
    },
    proofBannerIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: SURFACE,
      alignItems: 'center',
      justifyContent: 'center',
    },
    proofBannerText: { flex: 1, fontFamily: FontFamily.fredokaSemiBold, fontSize: 13, color: DARK, lineHeight: 18 },
    proofBannerLink: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 13, color: ORANGE },
    proofInfoBox: {
      backgroundColor: SURFACE,
      borderRadius: 12,
      padding: 12,
      marginTop: 8,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: DIVIDER,
    },
    proofInfoText: { fontFamily: FontFamily.fredokaRegular, fontSize: 13, color: MUTED, lineHeight: 19 },

    // ── Section headers ────────────────────────────────────────────────────
    sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 18, marginBottom: 10 },
    sectionIconWrap: { width: 30, height: 30, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    sectionTitle: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 15, color: DARK },
    sectionTitleDanger: { color: DANGER },
    sectionCount: {
      marginLeft: 'auto',
      fontFamily: FontFamily.fredokaSemiBold,
      fontSize: 12,
      color: MUTED,
      backgroundColor: ICON_BG,
      paddingHorizontal: 9,
      paddingVertical: 3,
      borderRadius: 999,
      minWidth: 28,
      textAlign: 'center',
      overflow: 'hidden',
    },

    // ── Task cards ─────────────────────────────────────────────────────────
    taskCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      padding: 14,
      borderRadius: 16,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: DIVIDER,
      marginBottom: 10,
      ...CARD_SHADOW,
    },
    taskCardOverdue: { borderLeftWidth: 4, borderLeftColor: DANGER },
    taskCardDone: { opacity: 0.6 },
    taskIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: ICON_BG,
      alignItems: 'center',
      justifyContent: 'center',
    },
    taskIconWrapDanger: { backgroundColor: DANGER_BG },
    taskIconWrapDone: { backgroundColor: SUCCESS_BG },
    taskContent: { flex: 1, gap: 4 },
    taskTitle: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 15, color: DARK, lineHeight: 20 },
    taskTitleDone: { textDecorationLine: 'line-through', color: MUTED },
    taskDesc: { fontFamily: FontFamily.fredokaRegular, fontSize: 13, color: MUTED, lineHeight: 18 },
    taskMetaRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 6, marginTop: 6 },

    duePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
      backgroundColor: ICON_BG,
    },
    duePillOverdue: { backgroundColor: DANGER_BG },
    duePillDone: { backgroundColor: SUCCESS_BG },
    duePillText: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 11, color: ORANGE },
    duePillTextOverdue: { color: DANGER },
    duePillTextDone: { color: GREEN },

    taskBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
      backgroundColor: WARNING_BG,
    },
    taskBadgeText: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 11, color: WARNING },
    taskBadgeRecur: { backgroundColor: INFO_BG },
    taskBadgeRecurText: { color: INFO },
    photoLink: { fontFamily: FontFamily.fredokaRegular, fontSize: 11, color: MUTED, marginTop: 4, fontStyle: 'italic' },

    markCompleteBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: ORANGE,
      paddingVertical: 9,
      paddingHorizontal: 14,
      borderRadius: 12,
    },
    markCompleteBtnDisabled: { backgroundColor: DIVIDER },
    markCompleteBtnText: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 12, color: '#fff' },
    markCompleteBtnTextDisabled: { color: MUTED },
    doneCheckWrap: { paddingTop: 2 },

    // ── Empty state ────────────────────────────────────────────────────────
    emptyWrap: { alignItems: 'center', paddingVertical: 56, paddingHorizontal: 32, gap: 8 },
    emptyIconWrap: { width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center', marginBottom: 4 },
    emptyTitle: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 16, color: DARK, textAlign: 'center' },
    emptyText: { fontFamily: FontFamily.fredokaRegular, fontSize: 13, color: MUTED, textAlign: 'center', lineHeight: 19, maxWidth: 260 },

    // ── Mark-complete modal ────────────────────────────────────────────────
    modalOverlay: {
      flex: 1,
      backgroundColor: OVERLAY,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalCenter: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', width: '100%' },
    modalCard: {
      width: '100%',
      maxWidth: 440,
      alignSelf: 'center',
      backgroundColor: SURFACE,
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: DIVIDER,
      ...CARD_SHADOW,
    },
    modalTitle: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 18, color: DARK, marginBottom: 8 },
    modalTaskTitle: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 16, color: DARK, marginBottom: 12 },
    reqPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      alignSelf: 'flex-start',
      backgroundColor: WARNING_BG,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      marginBottom: 12,
    },
    reqPillText: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 13, color: WARNING },
    modalHint: { fontFamily: FontFamily.fredokaRegular, fontSize: 13, color: MUTED, marginBottom: 12 },
    photoRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
    photoBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: DIVIDER,
      backgroundColor: SURFACE,
    },
    photoBtnText: { fontFamily: FontFamily.fredokaSemiBold, fontSize: 14, color: ORANGE },
    pickedLabel: { fontFamily: FontFamily.fredokaRegular, fontSize: 12, color: GREEN, marginBottom: 12 },
    modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, marginTop: 8 },
    modalCancel: { paddingVertical: 12, paddingHorizontal: 8 },
    modalCancelText: { fontFamily: FontFamily.fredokaSemiBold, color: MUTED },
    modalSave: {
      backgroundColor: ORANGE,
      paddingVertical: 12,
      paddingHorizontal: 22,
      borderRadius: 12,
      minWidth: 110,
      alignItems: 'center',
    },
    modalSaveText: { fontFamily: FontFamily.fredokaSemiBold, color: '#fff' },
  });
}

export type HelperWorkTasksStyles = ReturnType<typeof createHelperWorkTasksStyles>;
