import { StyleSheet } from 'react-native';

import { theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  listContent: { paddingBottom: 16, gap: 8 },
  empty: { textAlign: 'center', color: theme.color.muted, marginTop: 48, fontSize: 15, paddingHorizontal: 24 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: theme.color.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 12,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 14,
    borderRadius: 14,
    backgroundColor: theme.color.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.color.line,
    marginBottom: 8,
  },
  rowDone: { opacity: 0.55 },
  title: { fontSize: 16, fontWeight: '700', color: theme.color.ink },
  titleDone: { textDecorationLine: 'line-through', color: theme.color.muted },
  desc: { fontSize: 14, color: theme.color.inkMuted, marginTop: 4, lineHeight: 20 },
  descDone: { color: theme.color.muted },
  metaRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
  meta: { fontSize: 12, color: theme.color.muted },
  metaWarn: { fontSize: 12, color: theme.color.warning, fontWeight: '700' },
  photoLink: { fontSize: 11, color: theme.color.muted, marginTop: 4, fontStyle: 'italic' },

  instructionCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: theme.color.helperSoft,
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.color.line,
  },
  instructionTitle: { fontSize: 14, fontWeight: '800', color: theme.color.ink, marginBottom: 6 },
  instructionBody: { fontSize: 13, color: theme.color.inkMuted, lineHeight: 20 },
  checkInCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    marginTop: 12,
    backgroundColor: theme.color.helper,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
  },
  checkInCtaText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  restHint: { marginTop: 10, fontSize: 12, color: theme.color.muted, fontStyle: 'italic' },

  modalOverlay: {
    flex: 1,
    backgroundColor: theme.color.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCenter: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', width: '100%' },
  modalCard: {
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
    backgroundColor: theme.color.surfaceElevated,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.color.line,
    ...theme.shadow.card,
  },
  modalTitle: { fontSize: 18, fontWeight: '900', color: theme.color.ink, marginBottom: 8 },
  modalTaskTitle: { fontSize: 16, fontWeight: '700', color: theme.color.ink, marginBottom: 12 },
  reqPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    backgroundColor: theme.color.warningSoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    marginBottom: 12,
  },
  reqPillText: { fontSize: 13, fontWeight: '800', color: theme.color.warning },
  modalHint: { fontSize: 13, color: theme.color.muted, marginBottom: 12 },
  photoRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  photoBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.color.line,
    backgroundColor: theme.color.surface,
  },
  photoBtnText: { fontSize: 14, fontWeight: '700', color: theme.color.helper },
  pickedLabel: { fontSize: 12, color: theme.color.success, fontWeight: '600', marginBottom: 12 },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, marginTop: 8 },
  modalCancel: { paddingVertical: 12, paddingHorizontal: 8 },
  modalCancelText: { color: theme.color.muted, fontWeight: '700' },
  modalSave: {
    backgroundColor: theme.color.helper,
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 12,
    minWidth: 110,
    alignItems: 'center',
  },
  modalSaveText: { color: '#fff', fontWeight: '800' },
});
