import { Platform, StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

const isWeb = Platform.OS === 'web';

export const hireContractTermsStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: isWeb ? 'center' : 'flex-end',
    alignItems: isWeb ? 'center' : 'stretch',
    padding: isWeb ? 20 : 0,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: isWeb ? 16 : 0,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    width: isWeb ? 520 : '100%',
    maxWidth: isWeb ? 520 : '100%',
    alignSelf: isWeb ? 'center' : 'stretch',
    maxHeight: isWeb ? '92%' : '92%',
    overflow: 'hidden',
  },
  bodyPad: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 10 },
  title: { fontSize: 18, fontWeight: '700', color: theme.color.ink, marginBottom: 6 },
  sub: { fontSize: 13, color: theme.color.muted, lineHeight: 19, marginBottom: 4 },
  subBold: { fontWeight: '700', color: theme.color.ink },
  list: { paddingHorizontal: 18, marginBottom: 8 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.color.ink,
    marginTop: 18,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.line,
    paddingBottom: 4,
  },
  label: { fontSize: 13, fontWeight: '700', color: theme.color.ink, marginTop: 10, marginBottom: 4 },
  hint: { fontSize: 11, color: theme.color.muted, marginBottom: 6, lineHeight: 15 },
  input: {
    borderWidth: 1,
    borderColor: theme.color.line,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'ios' ? 10 : 8,
    fontSize: 15,
    color: theme.color.ink,
    backgroundColor: '#fff',
  },
  notes: {
    borderWidth: 1,
    borderColor: theme.color.line,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: theme.color.ink,
    backgroundColor: '#fff',
    minHeight: 80,
    maxHeight: 140,
  },
  salaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  currencyBox: {
    backgroundColor: '#F8F9FA',
    borderWidth: 1,
    borderColor: theme.color.line,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'ios' ? 10 : 8,
    borderRightWidth: 0,
  },
  currencyText: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.color.ink,
  },
  salaryInput: {
    flex: 1,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 4,
  },
  chip: {
    borderWidth: 1.5,
    borderColor: theme.color.line,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: '#fff',
  },
  chipActive: {
    borderColor: theme.color.success,
    backgroundColor: '#E8F5E9',
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.color.muted,
  },
  chipTextActive: {
    color: theme.color.success,
  },
  dayChip: {
    width: 42,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: theme.color.line,
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  dayChipActive: {
    borderColor: theme.color.success,
    backgroundColor: '#E8F5E9',
  },
  dayChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.color.muted,
  },
  dayChipTextActive: {
    color: theme.color.success,
  },
  btns: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 4, paddingHorizontal: 18, paddingBottom: 18 },
  cancel: { paddingVertical: 10, paddingHorizontal: 14 },
  cancelTxt: { fontSize: 15, fontWeight: '600', color: theme.color.muted },
  confirm: {
    backgroundColor: theme.color.success,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
  },
  confirmTxt: { color: '#fff', fontWeight: '700', fontSize: 15 },
});
