// components/helper/profile/profileEditModal/EditProfile.styles.ts

import { StyleSheet, Platform } from 'react-native';
// ============================================================================
// STYLES - SIMPLE & CLEAN
// ============================================================================

export const styles = StyleSheet.create({
  // Responsive Web
  // --- RESPONSIVE WEB WRAPPERS ---
  webOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  webContainer: {
    width: '100%',
    maxWidth: 900,
    maxHeight: '95%',
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#F8F9FA', // Assuming this is your background color
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  webSmallContainer: {
    width: '100%',
    maxWidth: 500, // Thinner for the pop-up selection modals
    maxHeight: '80%',
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  webRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
  },
  headerWeb: { paddingTop: 20 },
  contentWeb: { width: '100%' },
  footerWeb: { width: '100%' },

  // Standard Styles
  container: { 
    flex: 1, 
    backgroundColor: '#F8F9FA',
  },
  header: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center',
    padding: 20, 
    paddingTop: Platform.OS === 'ios' ? 60 : 20,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#EEF0F2',
  },
  title: { 
    fontSize: 22, 
    fontWeight: '800',
    color: '#1A1C1E',
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 13,
    color: '#6C757D',
    marginTop: 2,
  },
  closeBtn: {
    padding: 8,
    backgroundColor: '#F1F3F5',
    borderRadius: 12,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  loadingText: {
    marginTop: 12,
    color: '#666',
    fontSize: 15,
    fontWeight: '500',
  },
  content: {
    flex: 1,
  },
  section: {
    padding: 20,
    backgroundColor: '#fff',
    marginBottom: 16,
    borderRadius: 20,
    marginHorizontal: 16,
    marginTop: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    gap: 12,
  },
  sectionIconBg: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#EBF5FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionTitleText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1C1E',
  },
  inputGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  inputHalf: {
    flex: 1,
  },
  label: {
    fontSize: 14,
    fontWeight: '700',
    color: '#495057',
    marginBottom: 8,
    marginTop: 16,
  },
  requiredMark: {
    color: '#FF3B30',
    fontWeight: '700',
  },
  birthDateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1.5,
    borderColor: '#DEE2E6',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: '#fff',
    marginBottom: 4,
  },
  birthDateBtnText: {
    flex: 1,
    fontSize: 15,
    color: '#1A1C1E',
    fontWeight: '600',
  },
  birthDateBtnPlaceholder: {
    color: '#868E96',
    fontWeight: '500',
  },
  /** Web birth `<input type="date">` — spacing matches `LabeledInput` container */
  birthWebWrap: {
    marginBottom: 20,
  },
  infoAlert: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EBF5FF',
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
    gap: 10,
    borderWidth: 1,
    borderColor: '#D1E9FF',
  },
  infoAlertText: {
    fontSize: 13,
    color: '#007AFF',
    fontWeight: '600',
  },
  stepContainer: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F3F5',
    marginBottom: 8,
  },
  stepDisabled: {
    opacity: 0.6,
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  stepNumberContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepNumberDisabled: {
    backgroundColor: '#ADB5BD',
  },
  stepNumber: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  stepIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F1F3F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1C1E',
  },
  stepSubtitle: {
    fontSize: 12,
    color: '#6C757D',
    marginTop: 2,
  },
  stepActionBtn: {
    padding: 8,
  },
  tagList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingLeft: 40,
  },
  tagBadge: {
    backgroundColor: '#EBF5FF',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D1E9FF',
  },
  tagBadgeText: {
    color: '#007AFF',
    fontSize: 12,
    fontWeight: '700',
  },
  tagCustom: {
    backgroundColor: '#EBFBEE',
    borderColor: '#D3F9D8',
    flexDirection: 'row',
    alignItems: 'center',
  },
  tagCustomText: {
    color: '#2ECC71',
  },
  emptyTagText: {
    fontSize: 12,
    color: '#ADB5BD',
    fontStyle: 'italic',
  },
  horizontalScroll: {
    marginHorizontal: -4,
    marginTop: 8,
  },
  row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  option: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E9ECEF',
    backgroundColor: '#fff',
  },
  optionActive: {
    backgroundColor: '#007AFF',
    borderColor: '#007AFF',
  },
  optionText: {
    color: '#495057',
    fontSize: 14,
    fontWeight: '600',
  },
  optionTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  dotGreen: { backgroundColor: '#2ECC71' },
  dotOrange: { backgroundColor: '#FF9500' },
  dotRed: { backgroundColor: '#FF3B30' },
  salaryContainer: {
    marginTop: 8,
  },
  salaryHint: {
    fontSize: 12,
    color: '#6C757D',
    marginTop: -4,
    marginBottom: 12,
    fontStyle: 'italic',
  },
  photoSection: {
    alignItems: 'center',
    padding: 30,
    backgroundColor: '#fff',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    marginBottom: 8,
  },
  photoWrapper: {
    position: 'relative',
  },
  photoBorder: {
    padding: 4,
    borderRadius: 60,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  photo: {
    width: 110,
    height: 110,
    borderRadius: 55,
  },
  photoPlaceholder: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraIconContainer: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: '#007AFF',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#fff',
  },
  photoText: {
    marginTop: 16,
    color: '#007AFF',
    fontSize: 15,
    fontWeight: '700',
  },
  footer: {
    padding: 20,
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#EEF0F2',
  },
  saveBtn: {
    backgroundColor: '#007AFF',
    padding: 18,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  saveBtnDisabled: {
    backgroundColor: '#ADB5BD',
    shadowOpacity: 0,
  },
  savingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  saveText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 17,
    letterSpacing: 0.5,
  },

  // Modal styles
  modalContainer: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: Platform.OS === 'ios' ? 50 : 0,
  },
  modalHeader: {
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF0F2',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1A1C1E',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F3F5',
    margin: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    gap: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#1A1C1E',
    fontWeight: '600',
  },
  addCustomBtn: {
    padding: 4,
  },
  customSection: {
    backgroundColor: '#F8F9FA',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF0F2',
  },
  customSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#007AFF',
    margin: 20,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  emptyState: {
    padding: 80,
    alignItems: 'center',
  },
  emptyText: {
    color: '#ADB5BD',
    fontSize: 16,
    fontWeight: '600',
  },
  listItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F8F9FA',
  },
  listItemText: {
    fontSize: 16,
    color: '#1A1C1E',
    fontWeight: '600',
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    borderTopWidth: 1,
    borderTopColor: '#EEF0F2',
    backgroundColor: '#fff',
  },
  selectedCount: {
    fontSize: 15,
    color: '#6C757D',
    fontWeight: '700',
  },
  doneBtn: {
    backgroundColor: '#007AFF',
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 14,
  },
  doneText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
  },
});