import { Platform, StyleSheet } from 'react-native';

import type { ThemeColor } from '@/constants/theme';
import { theme } from '@/constants/theme';

export function createHelperWorkScheduleStyles(c: ThemeColor) {
  return StyleSheet.create({
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    scroll: { paddingBottom: 16 },
    requestBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: c.helper,
      paddingVertical: 14,
      borderRadius: 14,
      marginTop: 20,
    },
    requestBtnText: { color: '#fff', fontSize: 16, fontWeight: '800' },
    weekNav: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    navBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: c.helperSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    navBtnDisabled: { opacity: 0.35 },
    weekLabel: { fontSize: 15, fontWeight: '800', color: c.ink },
    cardList: { gap: 10 },
    dayCard: {
      borderRadius: 14,
      backgroundColor: c.surfaceElevated,
      borderWidth: 1,
      borderColor: c.line,
      padding: 14,
    },
    dayHead: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    dayHeadLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    statusDot: { width: 10, height: 10, borderRadius: 5 },
    dayName: { fontSize: 15, fontWeight: '800', color: c.ink },
    dayDate: { fontSize: 13, color: c.muted, fontWeight: '600' },
    dayBody: { gap: 4 },
    ok: { fontSize: 14, fontWeight: '700', color: c.success },
    time: { fontSize: 13, color: c.ink },
    timeOut: { fontSize: 13, color: c.muted },
    pendingOut: { fontSize: 13, color: c.warning, fontWeight: '600' },
    muted: { fontSize: 14, color: c.muted },
    statusLabel: { fontSize: 14, fontWeight: '700' },
    statusLeave: { color: c.warning },
    statusHoliday: { color: c.parent },
    modalOverlay: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: c.overlay,
      ...Platform.select({
        web: { justifyContent: 'center', padding: 20 },
        default: { justifyContent: 'flex-end' },
      }),
    },
    modalCard: {
      width: '100%',
      maxWidth: 520,
      alignSelf: 'center',
      backgroundColor: c.surfaceElevated,
      padding: 24,
      paddingBottom: 36,
      ...theme.shadow.card,
      ...Platform.select({
        web: { borderRadius: 20, maxHeight: '90%' as const },
        default: { borderTopLeftRadius: 20, borderTopRightRadius: 20 },
      }),
    },
    modalTitle: { fontSize: 20, fontWeight: '900', color: c.ink, marginBottom: 16 },
    modalLabel: {
      fontSize: 13,
      fontWeight: '800',
      color: c.muted,
      marginBottom: 8,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    datePickRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 12,
      padding: 14,
      marginBottom: 16,
    },
    datePickText: { flex: 1, fontSize: 16, fontWeight: '600', color: c.ink },
    reasonInput: {
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 12,
      padding: 14,
      fontSize: 16,
      color: c.ink,
      minHeight: 88,
      textAlignVertical: 'top',
      marginBottom: 20,
    },
    modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12 },
    modalCancel: { paddingVertical: 12, paddingHorizontal: 16 },
    modalCancelText: { color: c.muted, fontWeight: '700' },
    modalSubmit: {
      backgroundColor: c.helper,
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 12,
      minWidth: 120,
      alignItems: 'center',
    },
    modalSubmitDisabled: { opacity: 0.6 },
    modalSubmitText: { color: '#fff', fontWeight: '800', fontSize: 16 },
    balanceText: {
      fontSize: 15,
      fontWeight: '700',
      color: c.ink,
      marginBottom: 12,
      textAlign: 'center',
    },
    legendRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 12,
      justifyContent: 'center',
    },
    legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    legendDot: { width: 10, height: 10, borderRadius: 5 },
    legendText: { fontSize: 11, fontWeight: '600', color: c.muted },
    sheetSection: { marginTop: 12, gap: 4 },
    sheetLabel: { fontSize: 12, fontWeight: '800', color: c.muted, textTransform: 'uppercase' },
    sheetValue: { fontSize: 16, fontWeight: '600', color: c.ink },
    pickerWrap: {
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 12,
      marginBottom: 16,
      overflow: 'hidden',
    },
    picker: { width: '100%' },
    previewBox: {
      marginBottom: 16,
      padding: 12,
      borderRadius: 12,
      backgroundColor: c.helperSoft,
    },
    previewLine: { fontSize: 14, fontWeight: '700', color: c.ink },
    previewWarn: {
      marginTop: 8,
      fontSize: 13,
      fontWeight: '600',
      color: c.warning,
      lineHeight: 18,
    },
  });
}

export type HelperWorkScheduleStyles = ReturnType<typeof createHelperWorkScheduleStyles>;
