<?php
/**
 * HTML layout for the official PESO Ormoc "Kontrata sa Paglilingkod sa Tahanan"
 * (Form BK-1, RA 10361 — Batas Kasambahay), branded for CareLink.
 * All 18 numbered items are present; items 8, 9, 14, 16, 17, 18 carry the
 * fixed legal text required by PESO, printed verbatim in Filipino.
 *
 * @param array<string,mixed> $d Sanitized display values (pre-escaped where noted)
 */
function carelink_bk1_build_html(array $d): string
{
    $mark = static function ($flag) {
        return !empty($flag) ? '&#9745;' : '&#9744;'; // checked/unchecked box
    };
    $mSss = $mark($d['prov_sss'] ?? false);
    $mPh  = $mark($d['prov_ph'] ?? false);
    $mPi  = $mark($d['prov_pi'] ?? false);

    $dutiesHtml = '';
    $dutyItems = !empty($d['job_duties_items']) && is_array($d['job_duties_items'])
        ? $d['job_duties_items']
        : ['Mga gawain sa tahanan ayon sa napagkasunduan.'];
    foreach ($dutyItems as $i => $duty) {
        $letter = chr(97 + ($i % 26));
        $dutiesHtml .= '<div class="sub-item">' . $letter . '. ' . $duty . '</div>';
    }

    $minorNote = '';
    if (!empty($d['is_minor'])) {
        $minorNote = '<div class="fixed-note">(Para sa Kasambahay na edad 15 hanggang 17, hindi sila pinahihintulutang '
            . 'magtrabaho ng higit sa isang araw, 40 oras sa isang linggo, at sa pagitan ng alas diyes ng gabi '
            . 'hanggang ala sais ng umaga)</div>';
    }

    $employerSigDate = !empty($d['employer_signed_date']) ? $d['employer_signed_date'] : '_______________';
    $helperSigDate = !empty($d['helper_signed_date']) ? $d['helper_signed_date'] : '_______________';
    $appId = htmlspecialchars((string) ($d['application_id'] ?? ''), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    $docRef = $d['doc_ref'] ?? '';

    return '<!DOCTYPE html>
<html lang="fil">
<head>
  <meta charset="UTF-8" />
  <style>
    @page { margin: 2.5cm; }
    body { font-family: Arial, "DejaVu Sans", sans-serif; font-size: 11pt; line-height: 1.4; color: #1a1a1a; }
    .brand-header { text-align: center; margin-bottom: 14px; }
    .brand-name { font-size: 12pt; font-weight: bold; color: #2e7d32; }
    .brand-sub { font-size: 9.5pt; color: #555; margin-top: 2px; }
    h1 { font-family: Arial, "DejaVu Sans", sans-serif; font-size: 14pt; font-weight: bold; text-align: center; margin: 6px 0 2px 0; }
    .doc-ref { text-align: center; font-size: 8.5pt; color: #666; margin-bottom: 14px; }
    .intro { margin: 10px 0; }
    .party-block { margin: 4px 0 4px 14px; }
    .party-label { font-weight: bold; }
    .terms-lead { font-weight: bold; margin: 16px 0 10px 0; }
    .item { margin: 0 0 10px 0; }
    .item-num { font-weight: bold; }
    .sub-item { margin: 3px 0 0 18px; }
    .checks { margin: 4px 0 0 18px; }
    .fixed-note { font-style: italic; font-size: 10pt; color: #333; margin: 3px 0 0 18px; }
    .fixed-item { font-style: italic; font-size: 10pt; }
    .closing { margin: 16px 0 0 0; }
    .sig-table { width: 100%; border-collapse: collapse; margin-top: 36px; }
    .sig-table td { width: 50%; vertical-align: top; padding: 0 12px; }
    .sig-line { border-top: 1px solid #1a1a1a; margin-top: 46px; padding-top: 4px; text-align: center; font-size: 10pt; }
    .sig-line.first { margin-top: 36px; }
    .footer {
      position: fixed;
      bottom: -1.7cm;
      left: 0; right: 0;
      text-align: center;
      font-size: 8pt;
      color: #777;
      border-top: 1px solid #ccc;
      padding-top: 4px;
    }
  </style>
</head>
<body>
  <div class="footer">
    Generated by CareLink &middot; carelink.app &middot; Document ID: ' . $appId . '<br/>
    Ang kontratang ito ay sumusunod sa RA 10361 (Batas Kasambahay). Pinapayuhan ang dalawang panig na mag-ingat ng
    isang kopya at magsumite ng isang kopya sa Punong Barangay.
  </div>

  <div class="brand-header">
    <div class="brand-name">CareLink &mdash; Intelligent Domestic Helper Recruitment Platform</div>
    <div class="brand-sub">In partnership with PESO Ormoc City</div>
  </div>

  <h1>KONTRATA SA PAGLILINGKOD SA TAHANAN</h1>
  <div class="doc-ref">Document ID: ' . $docRef . '</div>

  <p class="intro">Ang Kontrata ng trabaho sa tahanan ay napagpasiyahan sa pagitan nina:</p>

  <div class="party-block">
    <div><span class="party-label">A. Pangalan ng Pinaglilingkuran (Employer):</span> ' . ($d['employer_name'] ?? 'N/A') . '</div>
    <div>Tirahan at Telepono: ' . ($d['employer_addr_phone'] ?? 'N/A') . '</div>
  </div>

  <div class="party-block">
    <div><span class="party-label">B. Pangalan ng Kasambahay (Helper):</span> ' . ($d['helper_name'] ?? 'N/A') . '</div>
    <div>Katayuang Sibil: ' . ($d['helper_civil'] ?? 'N/A') . ' &nbsp; | &nbsp; Edad: ' . ($d['helper_age'] ?? 'N/A') . '</div>
    <div>Tirahan at Telepono: ' . ($d['helper_addr_phone'] ?? 'N/A') . '</div>
  </div>

  <p class="terms-lead">Nagkasundo sa mga sumusunod na tuntunin at kondisyon:</p>

  <div class="item">
    <span class="item-num">1.</span> Lugar ng trabaho: ' . ($d['place_of_work'] ?? 'N/A') . '
    <div class="fixed-note">(Hindi maaaring italaga sa gawaing commercial, industrial o agricultural enterprise)</div>
  </div>

  <div class="item">
    <span class="item-num">2.</span> Tagal/Panahon ng trabaho:
    <div class="sub-item">Mula sa: ' . ($d['start_date'] ?? 'N/A') . '</div>
    <div class="sub-item">Hanggang sa: ' . ($d['end_date_display'] ?? 'N/A') . '</div>
  </div>

  <div class="item">
    <span class="item-num">3.</span> Uri ng trabaho: ' . ($d['job_title'] ?? 'N/A') . '
    <div class="fixed-note">(yaya, kusinera, hardinero, labandera, atbp.)</div>
  </div>

  <div class="item">
    <span class="item-num">4.</span> Mga tungkulin at gawain:
    ' . $dutiesHtml . '
  </div>

  <div class="item">
    <span class="item-num">5.</span> Oras ng trabaho: ' . ($d['work_hours'] ?? 'N/A') . '
    ' . $minorNote . '
  </div>

  <div class="item">
    <span class="item-num">6.</span> Lingguhang araw ng pahinga: ' . ($d['rest_days'] ?? 'N/A') . '
  </div>

  <div class="item">
    <span class="item-num">7.</span> Pasahod (Salary):
    <div class="sub-item">a. Halaga ng buwanang sahod: ' . ($d['salary_amount'] ?? 'N/A') . '</div>
    <div class="sub-item">b. Dagdag na sahod kapag lumampas sa itinakdang oras ng trabaho (halaga ng sahod bawat oras): ' . ($d['overtime_rate'] ?? 'N/A') . '</div>
    <div class="sub-item">c. Takdang araw ng pagbabayad ng sahod (petsa ng buwanang sahod): ' . ($d['payment_schedule'] ?? 'N/A') . '</div>
  </div>

  <div class="item">
    <span class="item-num">8.</span> Mga pinahihintulutang kaltas sa sahod:
    <div class="fixed-note">Kontribusyon sa PhilHealth, Pag-IBIG, at SSS kung ang sahod ay P5,000 pataas, ayon sa batas.</div>
    <div class="checks">' . $mSss . ' SSS &nbsp;&nbsp;&nbsp; ' . $mPh . ' PhilHealth &nbsp;&nbsp;&nbsp; ' . $mPi . ' Pag-IBIG</div>
  </div>

  <div class="item">
    <span class="item-num">9.</span> Mga benepisyo:
    <div class="sub-item fixed-item">a. Taunang leave na 5 araw na may bayad (dapat gamitin)</div>
    <div class="sub-item fixed-item">b. First-aid assistance kapag nagkasakit</div>
    <div class="fixed-note">Ayon sa kasunduan: Vacation leave &mdash; ' . ($d['vacation_leave_days'] ?? 5) . ' araw/taon; Sick leave &mdash; ' . ($d['sick_leave_days'] ?? 5) . ' araw/taon.</div>
  </div>

  <div class="item">
    <span class="item-num">10.</span> Iba pang benepisyo: ' . ($d['other_benefits'] ?? 'Wala') . '
  </div>

  <div class="item">
    <span class="item-num">11.</span> Kasunduan tungkol sa pagkakautang, kung meron man: ' . ($d['debt_agreement'] ?? 'Wala') . '
  </div>

  <div class="item">
    <span class="item-num">12.</span> Kasunduan tungkol sa gastos sa deployment, kung meron man:
    <div class="fixed-note">(Ang mga ginastos sa deployment ay makukuha muli ng pinaglilingkuran sa kasambahay kung siya ay hindi tumagal ng 6 na buwan sa pinaglilingkuran)</div>
    <div class="sub-item">' . ($d['deployment_agreement'] ?? 'Wala') . '</div>
  </div>

  <div class="item">
    <span class="item-num">13.</span> Kasunduan tungkol sa pagtatapos ng trabaho: ' . ($d['termination_conditions'] ?? 'Ayon sa RA 10361') . '
  </div>

  <div class="item">
    <span class="item-num">14.</span> Bayad sa pagwawakas ng trabaho/kontrata:
    <div class="fixed-note">Bayad ng 15 araw na sahod kung ang kasambahay ay tinanggal sa trabaho ng di-makatarungan, katumbas ng PHP ' . ($d['termination_pay'] ?? '0.00') . '.</div>
  </div>

  <div class="item">
    <span class="item-num">15.</span> Iba pang kasunduan, kung meron man: ' . ($d['other_agreements'] ?? 'Wala') . '
  </div>

  <div class="item fixed-item">
    <span class="item-num">16.</span> Kapag natapos ang termino ng kasunduan ay maaring awtomatikong ulitin ito at maging
    epektibo kung patuloy na maninilbihan ang kasambahay sa pinaglilingkuran.
  </div>

  <div class="item fixed-item">
    <span class="item-num">17.</span> Kung mangyari na may pagtalunan ang mgkabilang panig, ito ay maaring pagkasunduan
    muna sa barangay at kung walang mangyayari ay iaakyat ito sa DOLE-Regional/Provincial Field Office na nakasasakop
    sa lugar ng trabaho.
  </div>

  <div class="item fixed-item">
    <span class="item-num">18.</span> Ano mga pagbabago sa kasunduan ay may bisa lamang kung ito ay napagkasunduan at
    may katumbas na kasulatan na nilagdaan ng dalawang panig.
  </div>

  <p class="closing">Ang Pinaglilingkuran ay nangakong magbibigay sa Kasambahay ng lahat ng mga benepisyong itinakda sa ilalim ng batas.</p>
  <p class="closing">Ang Pinaglilingkuran at Kasambahay ay kusang sumasang-ayon sa mga kondisyong nabanggit sa kontratang ito.</p>

  <table class="sig-table">
    <tr>
      <td>
        <div class="sig-line first">' . ($d['employer_name'] ?? '') . '<br/>(Lagda ng Pinaglilingkuran)</div>
        <div class="sig-line">' . $employerSigDate . '<br/>(Petsa ng paglalagda)</div>
        <div class="sig-line">&nbsp;<br/>(Saksi)</div>
      </td>
      <td>
        <div class="sig-line first">' . ($d['helper_name'] ?? '') . '<br/>(Lagda ng Kasambahay)</div>
        <div class="sig-line">' . $helperSigDate . '<br/>(Petsa ng paglalagda)</div>
        <div class="sig-line">&nbsp;<br/>(Saksi)</div>
      </td>
    </tr>
  </table>
</body>
</html>';
}
