// app/(auth)/login.styles.ts
import { StyleSheet } from "react-native";
import { theme } from "@/constants/theme";

export const styles = StyleSheet.create({
  background: { flex: 1 },
  container: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: theme.space.xl,
    width: "100%",
    maxWidth: 460,
    alignSelf: "center",
  },
  kicker: {
    fontSize: theme.font.caption,
    fontWeight: "700",
    color: theme.color.parent,
    letterSpacing: 1.2,
    textAlign: "center",
    marginBottom: theme.space.sm,
    textTransform: "uppercase",
  },
  title: {
    fontSize: theme.font.title,
    fontWeight: "800",
    textAlign: "center",
    color: theme.color.ink,
    marginBottom: theme.space.sm,
  },
  subtitle: {
    fontSize: theme.font.body,
    textAlign: "center",
    color: theme.color.muted,
    marginBottom: theme.space.xxl,
    lineHeight: 22,
  },
  form: {
    backgroundColor: theme.color.surfaceElevated,
    borderRadius: theme.radius.lg,
    padding: theme.space.xxl,
    borderWidth: 1,
    borderColor: theme.color.line,
    ...theme.shadow.card,
  },
  input: {
    height: 50,
    borderColor: theme.color.line,
    borderWidth: 1,
    borderRadius: theme.radius.md,
    paddingHorizontal: theme.space.lg,
    marginBottom: theme.space.md,
    backgroundColor: theme.color.surfaceElevated,
    color: theme.color.ink,
    fontSize: theme.font.body,
  },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: 50,
    borderColor: theme.color.line,
    borderWidth: 1,
    borderRadius: theme.radius.md,
    marginBottom: theme.space.md,
    backgroundColor: theme.color.surfaceElevated,
    paddingHorizontal: theme.space.lg,
  },
  inputPassword: { flex: 1, height: "100%", color: theme.color.ink, fontSize: theme.font.body },
  eyeIcon: { paddingLeft: theme.space.sm },
  link: {
    color: theme.color.parent,
    fontSize: theme.font.small,
    textAlign: "right",
    marginBottom: theme.space.lg,
    fontWeight: "600",
  },
  button: {
    backgroundColor: theme.color.ink,
    paddingVertical: 14,
    borderRadius: theme.radius.md,
    alignItems: "center",
  },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  back: {
    textAlign: "center",
    marginTop: theme.space.xl,
    color: theme.color.muted,
    fontSize: theme.font.small,
    fontWeight: "600",
  },
});
