// app/(auth)/signup.styles.ts
import { StyleSheet } from "react-native";
import { theme } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.color.surface },
  keyboardView: { flex: 1, width: "100%" },
  background: { flex: 1, justifyContent: "center", alignItems: "center" },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: theme.space.xl,
    paddingVertical: theme.space.section,
  },
  card: {
    backgroundColor: theme.color.surfaceElevated,
    borderRadius: theme.radius.lg,
    padding: theme.space.xxl,
    width: "100%",
    maxWidth: 440,
    borderWidth: 1,
    borderColor: theme.color.line,
    ...theme.shadow.card,
  },
  closeButton: {
    position: "absolute",
    top: theme.space.md,
    right: theme.space.md,
    padding: theme.space.sm,
    zIndex: 10,
    borderRadius: theme.radius.full,
    backgroundColor: theme.color.surface,
  },
  closeText: { color: theme.color.muted, fontSize: 18, fontWeight: "600" },
  kicker: {
    fontSize: theme.font.caption,
    fontWeight: "700",
    color: theme.color.info,
    letterSpacing: 1,
    marginBottom: theme.space.sm,
    textTransform: "uppercase",
  },
  title: {
    fontSize: theme.font.title,
    fontWeight: "800",
    color: theme.color.ink,
    marginBottom: theme.space.sm,
  },
  subtitle: {
    fontSize: theme.font.small,
    color: theme.color.muted,
    marginBottom: theme.space.xl,
    lineHeight: 20,
  },
  roleBadgeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.space.md,
    paddingHorizontal: theme.space.lg,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    marginBottom: theme.space.xl,
    gap: theme.space.sm,
  },
  roleBadgeText: { fontSize: theme.font.body, fontWeight: "700" },
  label: {
    fontSize: theme.font.caption,
    fontWeight: "600",
    color: theme.color.inkMuted,
    marginBottom: theme.space.xs,
    marginLeft: 2,
  },
  input: {
    height: 48,
    borderColor: theme.color.line,
    borderWidth: 1,
    borderRadius: theme.radius.md,
    paddingHorizontal: theme.space.md,
    marginBottom: theme.space.md,
    backgroundColor: theme.color.surfaceElevated,
    color: theme.color.ink,
    fontSize: theme.font.body,
  },
  inputRow: { flexDirection: "row", width: "100%" },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: 48,
    borderColor: theme.color.line,
    borderWidth: 1,
    borderRadius: theme.radius.md,
    paddingHorizontal: theme.space.md,
    marginBottom: theme.space.md,
    backgroundColor: theme.color.surfaceElevated,
  },
  inputPassword: { flex: 1, height: "100%", color: theme.color.ink, fontSize: theme.font.body },
  eyeIcon: { paddingLeft: theme.space.sm },
  passwordRequirement: {
    paddingVertical: theme.space.sm,
    marginBottom: theme.space.md,
    backgroundColor: theme.color.surface,
    borderRadius: theme.radius.sm,
    paddingHorizontal: theme.space.md,
  },
  passwordRequirementText: { fontSize: 12, fontWeight: "500", lineHeight: 18 },
  button: {
    backgroundColor: theme.color.ink,
    paddingVertical: 14,
    borderRadius: theme.radius.md,
    alignItems: "center",
    marginTop: theme.space.sm,
  },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  loginText: { color: theme.color.muted, fontSize: theme.font.small, textAlign: "center", marginTop: theme.space.xl },
  link: { color: theme.color.parent, fontWeight: "700" },
  pickerContainer: { marginBottom: theme.space.md },
  pickerLabel: { color: theme.color.inkMuted, marginBottom: theme.space.xs, fontWeight: "600", fontSize: theme.font.caption },
  pickerWrapper: {
    backgroundColor: theme.color.surfaceElevated,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.color.line,
    overflow: "hidden",
  },
  picker: { height: 50, width: "100%", color: theme.color.ink },
});
