// app/(auth)/signup.styles.ts
import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  keyboardView: { flex: 1, width: "100%" },
  background: { flex: 1, justifyContent: "center", alignItems: "center" },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalBox: {
    backgroundColor: "rgba(255,255,255,0.85)",
    borderRadius: 12,
    padding: 20,
    width: "100%",
    maxWidth: 400,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
      },
      android: { elevation: 10 },
    }),
  },
  closeButton: { position: "absolute", top: 10, right: 10, padding: 3, zIndex: 10 },
  closeText: { color: "black", fontSize: 20, fontWeight: "bold" },
  title: { fontSize: 24, fontWeight: "700", textAlign: "center", color: "#000", marginBottom: 15 },
  
  roleBadgeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 20,
    gap: 8,
  },
  roleBadgeText: { fontSize: 15, fontWeight: "700" },

  input: {
    height: 45,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 15,
    backgroundColor: "#fff",
    color: "#000",
  },
  inputRow: { flexDirection: "row", width: "100%" },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: 45,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 15,
    backgroundColor: "#fff",
  },
  inputPassword: { flex: 1, height: "100%", color: "#000" },
  eyeIcon: { paddingLeft: 10 },
  passwordRequirement: { paddingTop: 0, padding: 5, marginBottom: 15 },
  button: { backgroundColor: "#4b4040ff", paddingVertical: 12, borderRadius: 8, alignItems: "center" },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
  loginText: { color: "black", fontSize: 14, textAlign: "center", marginTop: 15 },
  link: { color: "#09613cff", textDecorationLine: "underline" },
  statusText: { marginBottom: 10, textAlign: "center", fontWeight: "600" },
  
  pickerContainer: { marginBottom: 15 },
  pickerLabel: { color: "#333", marginBottom: 4, fontWeight: "600" },
  pickerWrapper: { backgroundColor: "#fff", borderRadius: 8, borderWidth: 1, borderColor: "#ccc" },
  picker: { height: 50, width: "100%", color: "#000" },
});