// app/(auth)/signup.styles.ts
import { Platform, StyleSheet } from "react-native";
import { theme } from "@/constants/theme";

/** Match login + one consistent “auth control” system on mobile */
const R = theme.radius.md;
const H = 50;
const CARD_R = theme.radius.lg;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.color.surface },
  keyboardView: { flex: 1, width: "100%" },
  background: { flex: 1, width: "100%" },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: theme.space.lg,
    paddingTop: theme.space.md,
    paddingBottom: theme.space.section * 2,
  },
  scrollContainerCompact: {
    paddingHorizontal: theme.space.md,
    paddingTop: theme.space.sm,
    paddingBottom: theme.space.section * 2.5,
  },
  card: {
    backgroundColor: theme.color.surfaceElevated,
    borderRadius: CARD_R,
    padding: theme.space.xxl,
    paddingTop: theme.space.section + theme.space.sm,
    width: "100%",
    maxWidth: 440,
    minWidth: 0,
    borderWidth: 1,
    borderColor: theme.color.line,
    ...theme.shadow.card,
  },
  cardCompact: {
    padding: theme.space.lg,
    paddingTop: theme.space.xl + theme.space.md,
  },
  closeButton: {
    position: "absolute",
    top: theme.space.md,
    right: theme.space.md,
    width: 40,
    height: 40,
    zIndex: 10,
    borderRadius: R,
    backgroundColor: theme.color.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.color.line,
    alignItems: "center",
    justifyContent: "center",
  },
  closeText: { color: theme.color.muted, fontSize: 16, fontWeight: "600" },
  kicker: {
    fontSize: theme.font.caption,
    fontWeight: "700",
    color: theme.color.info,
    letterSpacing: 1,
    marginBottom: theme.space.sm,
    textTransform: "uppercase",
  },
  title: {
    fontSize: theme.font.title,
    fontWeight: "800",
    color: theme.color.ink,
    marginBottom: theme.space.sm,
    lineHeight: 28,
  },
  titleCompact: {
    fontSize: theme.font.subtitle,
    lineHeight: 24,
  },
  subtitle: {
    fontSize: theme.font.small,
    color: theme.color.muted,
    marginBottom: theme.space.xl,
    lineHeight: 20,
  },
  subtitleCompact: {
    marginBottom: theme.space.lg,
    lineHeight: 19,
  },
  roleBadgeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minHeight: H,
    paddingVertical: theme.space.sm,
    paddingHorizontal: theme.space.lg,
    borderRadius: R,
    borderWidth: 1,
    marginBottom: theme.space.xl,
    gap: theme.space.sm,
    flexWrap: "wrap",
  },
  roleBadgeText: { fontSize: theme.font.body, fontWeight: "700", flexShrink: 1, textAlign: "center" },
  label: {
    fontSize: theme.font.caption,
    fontWeight: "600",
    color: theme.color.inkMuted,
    marginBottom: theme.space.xs,
    marginLeft: 2,
  },
  required: {
    color: theme.color.danger,
    fontWeight: "700",
  },
  optional: {
    color: theme.color.muted,
    fontWeight: "500",
  },
  input: {
    height: H,
    borderColor: theme.color.line,
    borderWidth: 1,
    borderRadius: R,
    paddingHorizontal: theme.space.lg,
    marginBottom: theme.space.md,
    backgroundColor: theme.color.surfaceElevated,
    color: theme.color.ink,
    fontSize: theme.font.body,
  },
  inputRow: { flexDirection: "row", width: "100%", alignItems: "flex-start" },
  inputRowStack: { flexDirection: "column" },
  inputRowField: { flex: 1, minWidth: 0 },
  inputRowFieldFull: { flex: 0, width: "100%" },
  inputRowGap: { width: theme.space.md },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: H,
    borderColor: theme.color.line,
    borderWidth: 1,
    borderRadius: R,
    paddingHorizontal: theme.space.lg,
    marginBottom: theme.space.md,
    backgroundColor: theme.color.surfaceElevated,
  },
  inputPassword: { flex: 1, height: "100%", color: theme.color.ink, fontSize: theme.font.body },
  eyeIcon: { paddingLeft: theme.space.sm },
  passwordRequirement: {
    paddingVertical: theme.space.md,
    marginBottom: theme.space.md,
    backgroundColor: theme.color.surface,
    borderRadius: R,
    paddingHorizontal: theme.space.lg,
    borderWidth: 1,
    borderColor: theme.color.line,
  },
  passwordRequirementText: { fontSize: 12, fontWeight: "500", lineHeight: 18 },
  button: {
    backgroundColor: theme.color.ink,
    height: H,
    borderRadius: R,
    alignItems: "center",
    justifyContent: "center",
    marginTop: theme.space.sm,
    overflow: "hidden",
  },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  loginText: {
    color: theme.color.muted,
    fontSize: theme.font.small,
    textAlign: "center",
    marginTop: theme.space.xl,
    lineHeight: 20,
  },
  link: { color: theme.color.parent, fontWeight: "700" },
  pickerContainer: { marginBottom: theme.space.md },
  pickerLabel: {
    color: theme.color.inkMuted,
    marginBottom: theme.space.xs,
    fontWeight: "600",
    fontSize: theme.font.caption,
  },
  pickerWrapper: {
    backgroundColor: theme.color.surfaceElevated,
    borderRadius: R,
    borderWidth: 1,
    borderColor: theme.color.line,
    overflow: "hidden",
    minWidth: 0,
    width: "100%",
    height: H,
    justifyContent: "center",
  },
  picker: {
    width: "100%",
    color: theme.color.ink,
    ...(Platform.OS === "ios" ? { height: H } : { minHeight: H }),
  },
});
