// app/(parent)/jobs.styles.ts
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  mainContent: { flex: 1 },
  desktopContentWrapper: { flex: 1, backgroundColor: '#F8F9FA' },
  desktopHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 32, paddingBottom: 0 },
  desktopPageTitle: { fontSize: 32, fontWeight: '700', color: '#1A1C1E' },
  desktopPostButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#007AFF', paddingVertical: 12, paddingHorizontal: 20, borderRadius: 12, gap: 8 },
  desktopPostButtonText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  mobileHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#E5E5EA' },
  menuButton: { padding: 8 },
  mobileTitle: { fontSize: 18, fontWeight: '700', color: '#1A1C1E' },
  postButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#007AFF', alignItems: 'center', justifyContent: 'center' },
  postButtonDisabled: { backgroundColor: '#ccc' },
  statsContainer: { flexDirection: 'row', backgroundColor: '#fff', paddingVertical: 16, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: '#F0F0F0' },
  statsContainerDesktop: { marginHorizontal: 32, marginTop: 24, borderRadius: 12, borderWidth: 1, borderColor: '#E5E5EA' },
  statBox: { flex: 1, alignItems: 'center' },
  statValue: { fontSize: 24, fontWeight: '700', color: '#1A1C1E', marginBottom: 4 },
  statLabel: { fontSize: 11, color: '#666', fontWeight: '600' },
  filterContainer: { flexDirection: 'row', backgroundColor: '#fff', paddingHorizontal: 12, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#F0F0F0', gap: 8 },
  filterContainerDesktop: { backgroundColor: 'transparent', borderBottomWidth: 0, paddingHorizontal: 32, paddingTop: 24 },
  filterTab: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 1, borderColor: '#E5E5EA', backgroundColor: '#fff' },
  filterTabActive: { backgroundColor: '#007AFF', borderColor: '#007AFF' },
  filterTabText: { fontSize: 13, fontWeight: '600', color: '#666' },
  filterTabTextActive: { color: '#fff' },
  listContent: { padding: 16, paddingBottom: 40 },
  listContentDesktop: { paddingHorizontal: 32, paddingTop: 16, paddingBottom: 60 },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },
  emptyText: { fontSize: 18, fontWeight: '700', color: '#1A1C1E', marginTop: 16, marginBottom: 8 },
  emptySubtext: { fontSize: 14, color: '#666', textAlign: 'center', marginBottom: 24 },
  postJobButton: { backgroundColor: '#007AFF', paddingVertical: 14, paddingHorizontal: 32, borderRadius: 12 },
  postJobButtonText: { color: '#fff', fontSize: 15, fontWeight: '700' },
});